Added documentation.
krvikas1011/method-parser pull request #15
Opened 2020-04-12 17:10 UTC by shubhaangi04

Documentation added for classes.

2020-04-13 12:59 UTC, thisissvikas requested changes

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/pom.xml
> +		</dependency>
Why are all these needed now if we are not doing testing?

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/pom.xml
> +    	<dependency>
Please use proper formatting.

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/cmd/CommandLineInterface.java
> + * To get user input.
This class will do much more than user input. It will handle all the command-line interactions.

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/cmd/CommandLineInterface.java
> +	 * @param args
elaborate please.

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/fetcher/OrgDetailsFetcher.java
> + * To get organization details.
Used to get

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/fetcher/OrgDetailsFetcher.java
> +     /**
Formatting

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/fetcher/OrgDetailsFetcher.java
> +	   * To get organization details of a user.
Of an org based on user details

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/fetcher/OrgDetailsFetcher.java
> +	   * @return Organization details for a user.
same as above.

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/fetcher/RepoDetailsFetcher.java
> +   * @throws ParseException
when?

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/fetcher/RepoDetailsFetcher.java
> +   * @return Repository details for a user.
why for a user?

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/fetcher/RepoDetailsFetcher.java
> +   * @throws ParseException
when?

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/fetcher/RepoDetailsFetcher.java
>      branchesUrl = branchesUrl.replaceAll("\\{.*\\}", "");
line comment to explain this.

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/fetcher/RepoDetailsFetcher.java
> +   * @throws ParseException
when?

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/fetcher/RepoDetailsFetcher.java
> +   * @throws ParseException
when?

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/manager/GITVersionControlManager.java
> +	 * To get the source details from user input.
for user input.

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/manager/GITVersionControlManager.java
> +	 * @param userInput : Input of user.
maintain lower case

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/manager/GITVersionControlManager.java
> +	 * @param userInput : Input of user.
and please write meaningful explanations for params not reiterate the name.

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/manager/VersionControlManager.java
> + * To generate an instance of {@link VersionControlManager}
Not useful.

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/manager/VersionControlManagerFactory.java
> + * Factory class to return the instance of {@link VersionControlManager}
based on what?

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/model/CommitHistory.java
> + * Model class for commit history of a repository.
We can see this is a class.

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/model/OrgDetails.java
> + * Model class for organization details.
we can see this is a class too.

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/model/RepoDetails.java
> + * Model class for source details.
we can see this is a class too.

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/model/SourceDetails.java
> + * Model class for source details.
ah.....we can see this is a class too.

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/model/UserInput.java
> + * Model class for user input.
we can see this is a class....

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/util/GITHandler.java
> +   * @throws ParseException
when?

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/util/GITHandler.java
> +   * @param repositoryName : Name of the repository.
wow, please make it meaningful

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/util/GITHandler.java
> +   * @param clientResponse : Output of the REST call made to the url.
link the instance, here and wherever needed

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/util/RESTCallHandler.java
> +@Path("RESTCallHandler")
This shows a lack of understanding of API concepts, remove this. This is not a controller.

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/main/java/com/vikas/method_parser/version_control_manager/details/fetcher/util/RESTCallHandler.java
> +    public static ClientResponse makeGETCall(@QueryParam("uri") String uri) {
All these not needed, revert please.

2020-04-13 12:59 UTC, krvikas1011 commented on sandbox/version-control-manager/src/test/java/HelloWorldTest.java
> +	}
Is this working? Even if it is, this is wrong? Please remove.

2020-04-19 08:04 UTC, thisissvikas approved these changes

2020-04-19 08:04 UTC, merged