Added code for ctags provider
krvikas1011/method-parser pull request #19
Opened 2020-04-25 15:05 UTC by shubhaangi04

2020-04-29 16:07 UTC, thisissvikas requested changes

2020-04-29 16:07 UTC, krvikas1011 commented on sandbox/tags-manager/src/main/java/com/vikas/method_parser/tags_manager/provider/CTAGSProvider.java
> +        Git.cloneRepository()
Extract this to a class

2020-04-29 16:07 UTC, krvikas1011 commented on sandbox/tags-manager/src/main/java/com/vikas/method_parser/tags_manager/util/FileOpertionsHandler.java
> +    public static String getTempUserDirectory() {
Can this be renamed.

2020-04-29 16:07 UTC, krvikas1011 commented on sandbox/tags-manager/src/main/java/com/vikas/method_parser/tags_manager/util/FileOpertionsHandler.java
> +    	String path = getTempUserDirectory() + "/Method_Parser_CTags";
Please de-couple

2020-05-03 10:58 UTC, krvikas1011 commented
Please rename this PR to what it actually is.

2020-05-07 16:23 UTC, closed without merging